//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginDashboard_MVC_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Job { get; set; }
        public string BaseLocation { get; set; }
        public string COE { get; set; }
        public string EmployeeNumber { get; set; }
    }
}
